services:
  - type: web
    name: medical-reference-app-mini
    env: python
    buildCommand: bash build-minimal.sh
    startCommand: gunicorn minimal:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
